#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ============================================================================
#  File:        nll_calib_probe_v1.py
#  Project:     Symmetry-Group Covariance Estimation for Adaptive Arrays
#  Brief:       Frobenius plug-in versus held-out likelihood calibration of the shrinkage.
#
#  Purpose
#    Determines how the shrinkage intensity should be chosen when the field
#    symmetry is only approximate, by comparing a covariance-error criterion
#    with a predictive criterion against the achievable envelope.
#
#  Description
#    For each snapshot count the intensity is set three ways: the closed-form
#    Frobenius mean-squared-error plug-in; a held-out Gaussian negative
#    log-likelihood minimized over a 21-point alpha grid; and the best grid
#    point judged by realized SINR loss, which is the envelope of the
#    shrinkage family. Folds are leave-one-out below K = 10 and five-fold
#    above. An alpha is admissible only when the training-fold estimate is
#    positive definite, with a fallback to alpha = 1 when none is. An
#    oracle-loaded sample covariance is carried as the external baseline.
#
#  Inputs
#    none; scenarios generated by stap_sinr_v3
#
#  Outputs
#    nll_calib.json  losses and selected intensities, both regimes
#
#  Usage
#    python3 nll_calib_probe_v1.py  # about four minutes
#
#  Version
#    Created:       bundle v6, 2026-09-01
#    Last modified: bundle v7.1, 2026-09-01
#
#  Revision history
#    v6     2026-09-01   created
#    v7.1   2026-09-01   source headers added
#
#  Author
#    Mitchell A. Thornton  <mitch@smu.edu>
#    ORCID 0000-0003-3559-9511
#
#  License
#    SPDX-License-Identifier: MIT
#    The MIT license grants copyright permissions only and grants no
#    rights under patents. See PATENTS.md.
#
#  Copyright (c) 2026 Mitchell A. Thornton
# ============================================================================

"""Held-out negative-log-likelihood calibration of the shrinkage intensity.

The closed-form Frobenius plug-in balances covariance mean-squared error. When a
strong off-commutant source is present the SINR loss is not aligned with that
criterion and the plug-in stays near the projection, inheriting its bias floor.
This probe adds a held-out Gaussian NLL calibration, which selects alpha by
predictive fit on snapshots not used to form the estimate, and compares:

  group     pure projection, alpha = 1
  frob      closed-form Frobenius-MSE plug-in (arXiv:2605.17111)
  nll       held-out NLL calibration over an alpha grid
  oracle    best alpha on the grid, judged by the realized SINR loss
  lsmi      diagonally loaded sample covariance at an oracle-tuned level

Folds: leave-one-out for K < 10, otherwise five folds. An alpha is admissible
only if the training-fold estimate is positive definite; if none is admissible
the calibration falls back to alpha = 1.
"""
import json
import numpy as np

import stap_sinr_v3 as S

ALPHA_GRID = np.linspace(0.0, 1.0, 21)
DL_GRID = np.logspace(-3.0, 2.0, 26)


def _folds(K):
    if K < 10:
        return [([j for j in range(K) if j != i], [i]) for i in range(K)]
    idx = np.arange(K)
    parts = np.array_split(idx, 5)
    return [([j for j in idx if j not in set(p.tolist())], p.tolist()) for p in parts]


def nll_alpha(X, Pm, alphas=ALPHA_GRID):
    """Select alpha by mean held-out Gaussian NLL; returns (alpha, admissible_count)."""
    M, K = X.shape
    if K < 2:
        return 1.0, 0
    scores = np.full(len(alphas), np.nan)
    for ai, a in enumerate(alphas):
        tot, nfold = 0.0, 0
        ok = True
        for tr, va in _folds(K):
            Xt = X[:, tr]
            St = (Xt @ Xt.conj().T) / len(tr)
            Rt = a * S.reynolds(St, Pm) + (1 - a) * St
            w = np.linalg.eigvalsh(Rt)
            if w[0] <= 1e-10 * max(w[-1], 1e-12):
                ok = False
                break
            Xv = X[:, va]
            Sv = (Xv @ Xv.conj().T) / len(va)
            sign, logdet = np.linalg.slogdet(Rt)
            tot += float(logdet + np.real(np.trace(np.linalg.solve(Rt, Sv))))
            nfold += 1
        if ok and nfold:
            scores[ai] = tot / nfold
    if np.all(np.isnan(scores)):
        return 1.0, 0
    return float(alphas[int(np.nanargmin(scores))]), int(np.sum(~np.isnan(scores)))


def run(M=16, J=4, rogue_az=None, rogue_inr_db=15.0, T=250,
        Ks=(4, 6, 8, 10, 12, 16, 24, 32, 48, 64), seed=21):
    rng = np.random.default_rng(seed)
    perms = S.subgroup_perms(M, J, reflections=True)
    Pm = [S.perm_mat(p) for p in perms]
    R = S.scenario_R(M, J, 30.0, 1.5, 0.0, rogue_az, rogue_inr_db)
    s = S.uca_steer(M, az=2 * np.pi / J * 0.30, r=1.5)
    Lc = np.linalg.cholesky(R)
    sinr_opt = np.real(s.conj() @ np.linalg.inv(R) @ s)

    def loss(Rhat):
        try:
            w = np.linalg.solve(Rhat, s)
        except np.linalg.LinAlgError:
            return np.nan
        return (np.abs(w.conj() @ s) ** 2 / np.real(w.conj() @ R @ w)) / sinr_opt

    out = {k: [] for k in ['group', 'frob', 'nll', 'oracle', 'lsmi']}
    out['Ks'] = list(Ks)
    out['a_frob'] = []
    out['a_nll'] = []
    out['a_oracle'] = []
    for K in Ks:
        acc = {k: [] for k in out if k not in ('Ks', 'a_frob', 'a_nll', 'a_oracle')}
        grid_acc = [[] for _ in ALPHA_GRID]
        dl_acc = [[] for _ in DL_GRID]
        af, an = [], []
        for _ in range(T):
            Z = (rng.standard_normal((M, K)) + 1j * rng.standard_normal((M, K))) / np.sqrt(2)
            X = Lc @ Z
            Sh = (X @ X.conj().T) / K
            G = S.reynolds(Sh, Pm)
            acc['group'].append(loss(G))
            a1 = S.shrink_intensity(X, Sh, G, perms)
            af.append(a1)
            acc['frob'].append(loss(a1 * G + (1 - a1) * Sh))
            a2, _ = nll_alpha(X, Pm)
            an.append(a2)
            acc['nll'].append(loss(a2 * G + (1 - a2) * Sh))
            for gi, a in enumerate(ALPHA_GRID):
                grid_acc[gi].append(loss(a * G + (1 - a) * Sh))
            sc = np.real(np.trace(Sh)) / M
            for j, c in enumerate(DL_GRID):
                dl_acc[j].append(loss(Sh + c * sc * np.eye(M)))

        def db(v):
            v = np.array(v, dtype=float)
            v = v[np.isfinite(v) & (v > 0)]
            return float(10 * np.log10(np.mean(v))) if v.size else None

        for k in ('group', 'frob', 'nll'):
            out[k].append(db(acc[k]))
        gd = [db(a) for a in grid_acc]
        bg = int(np.nanargmax([-1e9 if v is None else v for v in gd]))
        out['oracle'].append(gd[bg])
        out['a_oracle'].append(float(ALPHA_GRID[bg]))
        dd = [db(a) for a in dl_acc]
        out['lsmi'].append(max(v for v in dd if v is not None))
        out['a_frob'].append(float(np.mean(af)))
        out['a_nll'].append(float(np.mean(an)))
    out.update({'M': M, 'J': J, 'rogue_az': rogue_az, 'rogue_inr_db': rogue_inr_db,
                'dimC': S.commutant_dim(Pm, M), 'deff': M * M / S.commutant_dim(Pm, M)})
    return out


def _show(r, name):
    print(f"--- {name} (M={r['M']}, J={r['J']}, d_eff={r['deff']:.2f}) ---")
    print(f"{'K':>4} {'group':>8} {'frob':>8} {'nll':>8} {'oracle':>8} {'LSMI*':>8}"
          f" | {'a_frob':>7} {'a_nll':>7} {'a_orc':>7}")
    for i, K in enumerate(r['Ks']):
        def f(k):
            v = r[k][i]
            return f"{v:8.2f}" if v is not None else "       -"
        print(f"{K:>4} {f('group')} {f('frob')} {f('nll')} {f('oracle')} {f('lsmi')}"
              f" | {r['a_frob'][i]:7.3f} {r['a_nll'][i]:7.3f} {r['a_oracle'][i]:7.2f}")
    print()


if __name__ == "__main__":
    res = {}
    res['matched'] = run()
    res['mismatch'] = run(rogue_az=2 * np.pi / 4 * 0.62, rogue_inr_db=15.0)
    _show(res['matched'], "MATCHED")
    _show(res['mismatch'], "MISMATCH (off-orbit jammer at 15 dB)")
    json.dump(res, open('nll_calib.json', 'w'), indent=1)
