#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ============================================================================
#  File:        stap_tables_v2.py
#  Project:     Symmetry-Group Covariance Estimation for Adaptive Arrays
#  Brief:       Variance law, matched-subgroup ladder, and invertibility thresholds.
#
#  Purpose
#    Produces the supporting validations: that the estimator variance follows
#    the commutant dimension, that the effective dimension can be read from
#    the geometry, and that the group average becomes invertible at K|G| >= M.
#
#  Description
#    The variance law is checked in the identity-scaled case, where the
#    per-coordinate variance is constant and the reduction factor is exactly
#    d_eff, and on the colored jammer covariance, where it is not. The ladder
#    reports the commutant dimension of each dihedral subgroup of D_16, each
#    value computed by the rank of the Reynolds projector and cross-checked
#    against an independent count of orbits on ordered index pairs. The rank
#    check measures the smallest K at which the group average is positive
#    definite, for the full array group and for the subgroup used in the
#    experiments.
#
#  Inputs
#    none; scenarios generated by stap_sinr_v3
#
#  Outputs
#    stap_tables.json  variance law, ladder, k-to-3 dB, rank thresholds
#
#  Usage
#    python3 stap_tables_v2.py
#
#  Version
#    Created:       bundle v5, 2026-09-01
#    Last modified: bundle v7.2, 2026-09-01
#
#  Revision history
#    v5     2026-09-01   created; replaces stap_tables_v1.py
#    v5     2026-09-01   rank check reports the threshold per group
#                        rather than a single-snapshot fraction
#    v7.2   2026-09-01   source headers added
#
#  Author
#    Mitchell A. Thornton  <mitch@smu.edu>
#    ORCID 0000-0003-3559-9511
#
#  License
#    SPDX-License-Identifier: MIT
#    The MIT license grants copyright permissions only and grants no
#    rights under patents. See PATENTS.md.
#
#  Copyright (c) 2026 Mitchell A. Thornton
# ============================================================================

"""Tables and validations, built on stap_sinr_v3.

(1) variance_law: validates E||Rhat_G - R||_F^2 = c dim(C)/K and the d_eff
    variance-reduction ratio, in the identity-scaled case and on the colored
    jammer-scenario covariance.
(2) k_at_3dB: snapshots to reach -3 dB SINR loss for the sample covariance,
    oracle-loaded sample covariance, persymmetric average, and group average,
    across array sizes (Table I).
(3) deff_ladder: effective dimension of the matched subgroup ladder D_2, D_4,
    D_8, D_16 on a sixteen-element array, with an independent orbit-count check.
(4) rank check at a single snapshot, supporting the invertibility remark.

Writes stap_tables.json. Every reported number is produced here or by
stap_sinr_v3.py; nothing is asserted that this code does not compute.
"""
import json
import numpy as np

import stap_sinr_v3 as S


def variance_law(M=16, J=4, T=2000, Ks=(4, 8, 16, 32, 64, 128), white=False, seed=1):
    rng = np.random.default_rng(seed)
    perms = S.subgroup_perms(M, J, reflections=True)
    Pm = [S.perm_mat(p) for p in perms]
    dimC = S.commutant_dim(Pm, M)
    R = np.eye(M) if white else S.scenario_R(M, J, 30.0, 1.5)
    Lc = np.linalg.cholesky(R)
    out = {"M": M, "J": J, "dimC": dimC, "deff": M * M / dimC, "white": white,
           "Ks": list(Ks), "Kmse_group": [], "Kmse_scm": [], "ratio": []}
    for K in Ks:
        eg, es = [], []
        for _ in range(T):
            Z = (rng.standard_normal((M, K)) + 1j * rng.standard_normal((M, K))) / np.sqrt(2)
            X = Lc @ Z
            Sh = (X @ X.conj().T) / K
            G = S.reynolds(Sh, Pm)
            eg.append(np.linalg.norm(G - R, "fro") ** 2)
            es.append(np.linalg.norm(Sh - R, "fro") ** 2)
        eg, es = float(np.mean(eg)), float(np.mean(es))
        out["Kmse_group"].append(K * eg)
        out["Kmse_scm"].append(K * es)
        out["ratio"].append(es / eg)
    return out


def k_at_3dB(M=16, J=4, T=300, rogue_az=None, seed=2):
    Ks = [1, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16, 20, 24, 28, 32, 40, 48, 56, 64, 80, 96, 128]
    r = S.run(M=M, J=J, T=T, Ks=Ks, rogue_az=rogue_az, seed=seed)

    def cross(curve):
        if curve[0] is not None and curve[0] >= -3.0:
            return float(Ks[0])
        for i in range(1, len(Ks)):
            a, b = curve[i - 1], curve[i]
            if a is None or b is None:
                continue
            if a <= -3.0 <= b:
                return round(float(Ks[i - 1] + (Ks[i] - Ks[i - 1]) * (-3.0 - a) / (b - a)), 1)
        return None

    return {"M": M, "J": J, "dimC": r["dimC"], "deff": round(r["deff"], 2),
            "adaptive_gain_db": round(r["stats"]["adaptive_gain_db"], 1),
            "k3_scm": cross(r["scm"]), "k3_lsmi": cross(r["dl"]),
            "k3_persym": cross(r["persym"]), "k3_group": cross(r["group"])}


def deff_ladder(M=16, Js=(2, 4, 8, 16)):
    rows = []
    for J in Js:
        perms = S.subgroup_perms(M, J, reflections=True)
        Pm = [S.perm_mat(p) for p in perms]
        dc = S.commutant_dim(Pm, M)
        rows.append({"J": J, "order": len(perms), "dimC": dc,
                     "dimC_orbit_check": S.orbit_count(perms, M),
                     "deff": round(M * M / dc, 2)})
    return {"M": M, "rows": rows, "persym_deff": 2.0}


def rank_check(M=16, T=300, seed=3):
    """Smallest K at which the group average is positive definite, for each matched group.

    The orbit of K snapshots spans at most K|G| directions, so positive
    definiteness needs K|G| >= M generically. This measures the realized
    threshold for the full dihedral group of the array and for the D_4 subgroup
    used in the experiment.
    """
    rng = np.random.default_rng(seed)
    R = S.scenario_R(M, 4, 30.0, 1.5)
    Lc = np.linalg.cholesky(R)
    out = []
    groups = [("D_%d (full)" % M, S.dihedral_perms(M)),
              ("D_4 (subgroup)", S.subgroup_perms(M, 4, reflections=True))]
    for name, perms in groups:
        Pm = [S.perm_mat(p) for p in perms]
        rec = {"group": name, "order": len(perms), "M": M, "by_K": []}
        for K in (1, 2, 3, 4):
            mins = []
            for _ in range(T):
                Z = (rng.standard_normal((M, K)) + 1j * rng.standard_normal((M, K))) / np.sqrt(2)
                X = Lc @ Z
                G = S.reynolds((X @ X.conj().T) / K, Pm)
                mins.append(np.linalg.eigvalsh(G)[0].real)
            mins = np.array(mins)
            rec["by_K"].append({"K": K, "min_eig_mean": float(mins.mean()),
                                "min_eig_min": float(mins.min()),
                                "pd_fraction": float((mins > 1e-9).mean())})
        out.append(rec)
    return out


if __name__ == "__main__":
    out = {}
    vw = variance_law(white=True)
    vc = variance_law(white=False)
    out["variance_law_white"] = vw
    out["variance_law_colored"] = vc
    print(f"VARIANCE LAW (D_4 on M=16): dimC={vw['dimC']}  d_eff={vw['deff']:.2f}")
    print(" K        :" + "".join(f"{k:8d}" for k in vw["Ks"]))
    print(" K*MSE_grp:" + "".join(f"{v:8.2f}" for v in vw["Kmse_group"]) + "  (-> dimC)")
    print(" K*MSE_scm:" + "".join(f"{v:8.1f}" for v in vw["Kmse_scm"]) + "  (-> M^2)")
    print(" ratio    :" + "".join(f"{v:8.2f}" for v in vw["ratio"]) + "  (-> d_eff)")
    print(" colored ratio:" + "".join(f"{v:8.2f}" for v in vc["ratio"]))

    print("\nK to reach -3 dB SINR loss vs aperture (four jammers on a D_4 orbit):")
    print(" M    dimC  d_eff  gain(dB)   SCM   LSMI*  persym  group")
    rows = []
    for M in (12, 16, 24, 32):
        r = k_at_3dB(M=M)
        rows.append(r)

        def f(v):
            return f"{v:6.1f}" if v is not None else "     -"
        print(f"{M:3d} {r['dimC']:6d} {r['deff']:6.2f} {r['adaptive_gain_db']:8.1f}"
              f" {f(r['k3_scm'])} {f(r['k3_lsmi'])} {f(r['k3_persym'])} {f(r['k3_group'])}")
    out["k3"] = rows

    lad = deff_ladder()
    out["deff_ladder"] = lad
    print("\nMatched-subgroup ladder on a sixteen-element array:")
    print("  group   |G|   dimC  (orbit check)  d_eff")
    for row in lad["rows"]:
        print(f"   D_{row['J']:<4d} {row['order']:4d} {row['dimC']:6d} "
              f"{row['dimC_orbit_check']:14d} {row['deff']:7.2f}")
    print(f"   persymmetric (Z_2)                       {lad['persym_deff']:7.2f}")

    rc = rank_check()
    out["rank_check"] = rc
    print("\nPositive definiteness of the group average versus K:")
    for rec in rc:
        cells = "  ".join(f"K={b['K']}: {b['pd_fraction']:.2f}" for b in rec["by_K"])
        print(f"  {rec['group']:16s} |G|={rec['order']:3d}   {cells}")

    json.dump(out, open("stap_tables.json", "w"), indent=1)
