#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ============================================================================
#  File:        stap_scaling_v1.py
#  Project:     Symmetry-Group Covariance Estimation for Adaptive Arrays
#  Brief:       Aperture sweep for a fixed and a growing field symmetry order.
#
#  Purpose
#    Tests the sample-complexity law by sweeping the array size under two
#    scenario families and comparing the measured snapshot requirement with
#    the prediction 2M/d_eff.
#
#  Description
#    Family one holds the field symmetry order fixed at J = 4 for every M, so
#    the effective dimension stays near 7.5 while the array grows. Family two
#    sets J = M/4, so the matched group order grows with the aperture and the
#    effective dimension grows as about M/2. For each cell the snapshots
#    needed to reach 3 dB of SINR loss are found by linear interpolation on
#    the loss curve, for the sample covariance, the oracle-loaded sample
#    covariance, the persymmetric average and the group average.
#
#  Inputs
#    none; scenarios generated by stap_sinr_v3.run
#
#  Outputs
#    stap_scaling.json  one record per aperture and family
#
#  Usage
#    python3 stap_scaling_v1.py     # about eight minutes
#
#  Version
#    Created:       bundle v6, 2026-09-01
#    Last modified: bundle v7.2, 2026-09-01
#
#  Revision history
#    v6     2026-09-01   created
#    v7.2   2026-09-01   source headers added
#
#  Author
#    Mitchell A. Thornton  <mitch@smu.edu>
#    ORCID 0000-0003-3559-9511
#
#  License
#    SPDX-License-Identifier: MIT
#    The MIT license grants copyright permissions only and grants no
#    rights under patents. See PATENTS.md.
#
#  Copyright (c) 2026 Mitchell A. Thornton
# ============================================================================

"""Sample complexity when the field symmetry order grows with the aperture.

Two families of scenarios are swept over array size.

  fixed symmetry    J = 4 jammers on a D_4 orbit for every M, so the matched
                    group order is constant and d_eff stays near 7.5
  growing symmetry  J = M/4 jammers on a D_{M/4} orbit, so the matched group
                    order grows with the array and d_eff grows as about M/2

For each, the snapshots needed to reach 3 dB of SINR loss are reported for the
sample covariance, the oracle-loaded sample covariance, the persymmetric
average, and the group average. The question the sweep answers is whether the
group advantage over diagonal loading persists at large aperture, which it does
only when the symmetry order grows with the array.

Writes stap_scaling.json.
"""
import json
import numpy as np

import stap_sinr_v3 as S

KS = [1, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16, 20, 24, 28, 32, 40, 48, 56, 64, 80, 96, 128, 160, 224]


def cross3(curve, Ks=KS):
    if curve[0] is not None and curve[0] >= -3.0:
        return float(Ks[0])
    for i in range(1, len(Ks)):
        a, b = curve[i - 1], curve[i]
        if a is None or b is None:
            continue
        if a <= -3.0 <= b:
            return round(float(Ks[i - 1] + (Ks[i] - Ks[i - 1]) * (-3.0 - a) / (b - a)), 1)
    return None


def sweep(family, Ms=(16, 24, 32, 48), T=300, seed=31):
    rows = []
    for M in Ms:
        J = 4 if family == "fixed" else M // 4
        r = S.run(M=M, J=J, T=T, Ks=KS, seed=seed)
        rows.append({"M": M, "J": J, "order": 2 * J, "dimC": r["dimC"],
                     "deff": round(r["deff"], 2),
                     "adaptive_gain_db": round(r["stats"]["adaptive_gain_db"], 1),
                     "k3_scm": cross3(r["scm"]), "k3_lsmi": cross3(r["dl"]),
                     "k3_persym": cross3(r["persym"]), "k3_group": cross3(r["group"])})
    return rows


def _show(rows, name):
    print(f"--- {name} ---")
    print(f"{'M':>4} {'J':>3} {'dimC':>6} {'d_eff':>7} {'gain':>6}"
          f" {'SCM':>7} {'LSMI*':>7} {'persym':>7} {'group':>7} {'LSMI*/group':>12}")
    for r in rows:
        def f(v):
            return f"{v:7.1f}" if v is not None else "      -"
        ratio = (r['k3_lsmi'] / r['k3_group']) if (r['k3_lsmi'] and r['k3_group']) else None
        rs = f"{ratio:12.2f}" if ratio else "           -"
        print(f"{r['M']:>4} {r['J']:>3} {r['dimC']:>6} {r['deff']:>7.2f}"
              f" {r['adaptive_gain_db']:>6.1f} {f(r['k3_scm'])} {f(r['k3_lsmi'])}"
              f" {f(r['k3_persym'])} {f(r['k3_group'])}{rs}")
    print()


if __name__ == "__main__":
    out = {}
    out["fixed"] = sweep("fixed")
    out["growing"] = sweep("growing")
    _show(out["fixed"], "FIXED symmetry order (J = 4 for every M)")
    _show(out["growing"], "GROWING symmetry order (J = M/4)")
    json.dump(out, open("stap_scaling.json", "w"), indent=1)
